package com.zcl.somecode.concurrent.exception;

public class ExceptionDemo {
	public static void main(String args[]) throws Exception{
//	   	 try{
//	   	    Bank ba=new Bank(50);
//	          ba.withdrawal(100);
//	          System.out.println("Withdrawal successful!");
//	      }catch(InsufficientFundsException e) { 
//	          System.out.println(e.toString());
//	          System.out.println(e.excepMessage());
//	          try {
//				throw new Exception();
//			} catch (Exception e1) {
//				e1.printStackTrace();
//			}
//	      }
	throw new Exception();   
	}
}
